version: 2

models:
  - name: dim_hosts_cleansed
    description: Cleansed table for the Airbnb hosts
    columns:
      - name: host_id
        description: The id of the host. This is the primary key.
        tests:
          - not_null
          - unique
      
      - name: host_name
        description: The name of the host.
        tests:
          - not_null
      
      - name: is_superhost
        description: Defines whether the host is a superhost.
        tests:
          - accepted_values:
              values: ['t', 'f']

  - name: dim_listings_cleaned
    description: Cleaned table which contains Aribnb listings.
    columns:
      - name: listing_id
        description: Primary key for the listings
        tests:
          - unique
          - not_null

      - name: host_id
        description: The hosts' ID. References the host table/
        tests:
          - not_null
          - relationships:
              to: ref('dim_hosts_cleaned')
              field: host_id

      - name: room_type
        description: Type of the apartment / room.
        tests:
          - accepted_values: 
              values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']

      - name: minimum_nights
        description: '{{ doc("dim_listings_cleaned__minimum_nights") }}'
        tests:
          - positive_value